import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-8`}>
        <header>
          <nav>
            <ul className="flex gap-4 flex-wrap">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/restaurants">Restaurants</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="py-8">{children}</main>
      </body>
    </html>
  );
}
